# Generated by Django 5.2.15 on 2026-06-16 01:24

import django.db.models.deletion
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('urlapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClickEvent',
            fields=[
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('accept_language', models.CharField(blank=True, default='', max_length=255)),
                ('referrer', models.TextField(blank=True, default='')),
                ('country_code', models.CharField(blank=True, default='', max_length=2)),
                ('region', models.CharField(blank=True, default='', max_length=128)),
                ('city', models.CharField(blank=True, default='', max_length=128)),
                ('timezone', models.CharField(blank=True, default='', max_length=64)),
                ('isp', models.CharField(blank=True, default='', max_length=255)),
                ('asn', models.CharField(blank=True, default='', max_length=64)),
                ('is_proxy', models.BooleanField(null=True)),
                ('is_hosting', models.BooleanField(null=True)),
                ('is_mobile', models.BooleanField(null=True)),
                ('enrichment_status', models.CharField(choices=[('PENDING', 'Pending'), ('DONE', 'Done'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=10)),
                ('enriched_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('clicked_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('accessed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clicks', to=settings.AUTH_USER_MODEL)),
                ('short_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='urlapp.shortlink')),
            ],
            options={
                'ordering': ['-clicked_at'],
                'indexes': [models.Index(fields=['short_link', '-clicked_at'], name='metrics_cli_short_l_b9b63f_idx')],
            },
        ),
    ]
