services:
  - type: web
    name: url-shortener
    runtime: python
    plan: free
    healthCheckPath: /
    buildCommand: |
      pip install -r requirements.txt
      npm ci --prefix frontend
      npm run build --prefix frontend
      python3 manage.py collectstatic --noinput
      python3 manage.py makemessages -l en -l uk && python3 manage.py compilemessages
    startCommand: gunicorn config.wsgi:application
    preDeployCommand: python manage.py migrate
    envVars:
      - key: DATABASE_URL
        sync: false
