services:
  - type: web
    name: url-shortener
    runtime: docker
    plan: free
    healthCheckPath: /
    preDeployCommand: python manage.py migrate
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ridicuoslylong.link
      - key: CSRF_TRUSTED_ORIGINS
        value: https://ridicuoslylong.link
      - key: DATABASE_URL
        sync: false
