services:
  - type: web
    name: url-shortener
    runtime: docker
    plan: starter
    healthCheckPath: /
    preDeployCommand: python manage.py migrate
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: yourdomain.com
      - key: CSRF_TRUSTED_ORIGINS
        value: https://yourdomain.com
      - key: DATABASE_URL
        fromDatabase:
          name: url-shortener-db
          property: connectionString

databases:
  - name: url-shortener-db
    plan: free
