# Generated by Django 5.2.15 on 2026-06-16 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_accept_language_profile_asn_profile_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='origin_updated_at',
        ),
    ]
