# Generated by Django 2.2 on 2019-04-21 21:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Surl',
            fields=[
                ('short_url', models.SlugField(max_length=6, primary_key=True, serialize=False)),
                ('given_url', models.URLField(max_length=300)),
                ('visit_count', models.IntegerField(default=0)),
                ('creat_date', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
