# Generated by Django 5.2.15 on 2026-06-16 00:45

import django.core.validators
import django.db.models.deletion
import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_profile_accept_language_profile_asn_profile_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortLink',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=20, unique=True)),
                ('given_url', models.URLField(max_length=500, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])])),
                ('visit_count', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='links', to='users.profile')),
            ],
            options={
                'indexes': [models.Index(fields=['-visit_count', '-created_date'], name='urlapp_shortlink_visit_c_idx')],
            },
        ),
    ]
